### ISSUE TITLE
Cannot run migrations with the percona extension on a Spring Boot app with embedded Tomcat

### ISSUE THREAD

**Issue by jogaco** [adangel/liquibase-percona#12]
I was trying out this extension.

However, when I add it to my maven dependencies and try it out, I get this:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed for change set db/db-20170709_150135.changelog.xml::1499605306898-1::myuser (generated):
     Reason: java.lang.RuntimeException: Percona exited with 255
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1081) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:856) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at com.operatornew.gamemanager.SpringBootMysqlApplication.main(SpringBootMysqlApplication.java:10) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:527) [spring-boot-maven-plugin-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set db/db-20170709_150135.changelog.xml::1499605306898-1::myuser (generated):
     Reason: java.lang.RuntimeException: Percona exited with 255
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:619) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:79) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:214) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:192) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:431) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388) ~[liquibase-core-3.5.3.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	... 24 common frames omitted
Caused by: java.lang.RuntimeException: Percona exited with 255
	at liquibase.ext.percona.PTOnlineSchemaChangeStatement.generate(PTOnlineSchemaChangeStatement.java:210) ~[liquibase-percona-1.3.0.jar:na]
	at liquibase.sqlgenerator.core.RuntimeGenerator.generateSql(RuntimeGenerator.java:19) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.sqlgenerator.core.RuntimeGenerator.generateSql(RuntimeGenerator.java:10) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.sqlgenerator.SqlGeneratorChain.generateSql(SqlGeneratorChain.java:30) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:225) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.executor.AbstractExecutor.applyVisitors(AbstractExecutor.java:25) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.access$500(JdbcExecutor.java:36) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:295) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:113) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1277) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1259) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:582) ~[liquibase-core-3.5.3.jar:na]
	... 32 common frames omitted

```

The migrations run fine without the extension.
They also run fine by manually running pt-online-schema-change.
Any tips on how to fix this?
Environment is Ubuntu.

**Comment by adangel** [comment]
We need to figure out, why `Percona exited with 255`...

Can you run the "updateSQL" command of liquibase and check the resulting pt-online-schema-change command, that would be executed? It should be contained in the generated SQL file as a comment.

It also might help to enable logging for "liquibase.*" - if pt-osc did output anything before exiting, it should end up in the logging channels of liquibase.

**Comment by jogaco** [comment]
Thanks for quick reply!

Seems that the passwd doesn't reach pt-osc.
I remark that this works fine without the percona plugin.
The relevant pt-osc commands are logged.

```
2017-07-09 21:22:48.636  WARN 17592 --- [           main] liquibase                                : classpath:db/db.changelog.xml: db/db-20170709_150135.changelog.xml::1499605306898-1::myuser (generated): Couldn't determine the password from JdbcConnection

java.lang.IllegalArgumentException: Can not set java.util.Properties field com.mysql.jdbc.ConnectionImpl.props to com.sun.proxy.$Proxy70
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[na:1.8.0_131]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[na:1.8.0_131]
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[na:1.8.0_131]
	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36) ~[na:1.8.0_131]
	at java.lang.reflect.Field.get(Field.java:393) ~[na:1.8.0_131]
	at liquibase.ext.percona.DatabaseConnectionUtil.getPassword(DatabaseConnectionUtil.java:98) ~[liquibase-percona-1.3.0.jar:na]
	at liquibase.ext.percona.PTOnlineSchemaChangeStatement.buildCommand(PTOnlineSchemaChangeStatement.java:126) [liquibase-percona-1.3.0.jar:na]
	at liquibase.ext.percona.PTOnlineSchemaChangeStatement.generate(PTOnlineSchemaChangeStatement.java:175) [liquibase-percona-1.3.0.jar:na]
	at liquibase.sqlgenerator.core.RuntimeGenerator.generateSql(RuntimeGenerator.java:19) [liquibase-core-3.5.3.jar:na]
	at liquibase.sqlgenerator.core.RuntimeGenerator.generateSql(RuntimeGenerator.java:10) [liquibase-core-3.5.3.jar:na]
	at liquibase.sqlgenerator.SqlGeneratorChain.generateSql(SqlGeneratorChain.java:30) [liquibase-core-3.5.3.jar:na]
	at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:225) [liquibase-core-3.5.3.jar:na]
	at liquibase.executor.AbstractExecutor.applyVisitors(AbstractExecutor.java:25) [liquibase-core-3.5.3.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.access$500(JdbcExecutor.java:36) [liquibase-core-3.5.3.jar:na]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:295) [liquibase-core-3.5.3.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55) [liquibase-core-3.5.3.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:113) [liquibase-core-3.5.3.jar:na]
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1277) [liquibase-core-3.5.3.jar:na]
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1259) [liquibase-core-3.5.3.jar:na]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:582) [liquibase-core-3.5.3.jar:na]
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51) [liquibase-core-3.5.3.jar:na]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:79) [liquibase-core-3.5.3.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:214) [liquibase-core-3.5.3.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:192) [liquibase-core-3.5.3.jar:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:431) [liquibase-core-3.5.3.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388) [liquibase-core-3.5.3.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) [spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) [spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) [spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) [spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) [spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296) [spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1081) [spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:856) [spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) [spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at com.operatornew.gamemanager.SpringBootMysqlApplication.main(SpringBootMysqlApplication.java:10) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:527) [spring-boot-maven-plugin-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

2017-07-09 21:22:48.638  INFO 17592 --- [           main] liquibase                                : classpath:db/db.changelog.xml: db/db-20170709_150135.changelog.xml::1499605306898-1::myuser (generated): Executing: pt-online-schema-change --alter="ADD COLUMN version INT NULL" --alter-foreign-keys-method=auto --host=localhost --port=3306 --user=root --execute D=game_manager,t=game
2017-07-09 21:22:48.966  INFO 17592 --- [       Thread-3] liquibase                                : classpath:db/db.changelog.xml: db/db-20170709_150135.changelog.xml::1499605306898-1::myuser (generated): Cannot connect to MySQL: DBI connect('game_manager;host=localhost;port=3306;mysql_read_default_group=client','root',...) failed: Access denied for user 'root'@'localhost' (using password: NO) at /usr/bin/pt-online-schema-change line 2296.
2017-07-09 21:22:48.966  INFO 17592 --- [       Thread-3] liquibase                                : classpath:db/db.changelog.xml: db/db-20170709_150135.changelog.xml::1499605306898-1::myuser (generated): 
2017-07-09 21:22:48.972  INFO 17592 --- [           main] liquibase                                : classpath:db/db.changelog.xml: db/db-20170709_150135.changelog.xml::1499605306898-1::myuser (generated): 
2017-07-09 21:22:48.974 ERROR 17592 --- [           main] liquibase                                : classpath:db/db.changelog.xml: db/db-20170709_150135.changelog.xml::1499605306898-1::myuser (generated): Change Set db/db-20170709_150135.changelog.xml::1499605306898-1::myuser (generated) failed.  Error: Percona exited with 255
2017-07-09 21:22:49.081  INFO 17592 --- [           main] liquibase                                : db/db-20170709_150135.changelog.xml::1499605306898-1::myuser (generated): Successfully released change log lock
2017-07-09 21:22:49.083  WARN 17592 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed for change set db/db-20170709_150135.changelog.xml::1499605306898-1::myuser (generated):
     Reason: java.lang.RuntimeException: Percona exited with 255
2017-07-09 21:22:49.090  INFO 17592 --- [           main] o.apache.catalina.core.StandardService   : Stopping service Tomcat
2017-07-09 21:22:49.125  INFO 17592 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-07-09 21:22:49.131 ERROR 17592 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed for change set db/db-20170709_150135.changelog.xml::1499605306898-1::myuser (generated):
     Reason: java.lang.RuntimeException: Percona exited with 255
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1081) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:856) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at com.operatornew.gamemanager.SpringBootMysqlApplication.main(SpringBootMysqlApplication.java:10) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:527) [spring-boot-maven-plugin-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set db/db-20170709_150135.changelog.xml::1499605306898-1::myuser (generated):
     Reason: java.lang.RuntimeException: Percona exited with 255
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:619) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:79) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:214) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:192) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:431) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388) ~[liquibase-core-3.5.3.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	... 24 common frames omitted
Caused by: java.lang.RuntimeException: Percona exited with 255
	at liquibase.ext.percona.PTOnlineSchemaChangeStatement.generate(PTOnlineSchemaChangeStatement.java:210) ~[liquibase-percona-1.3.0.jar:na]
	at liquibase.sqlgenerator.core.RuntimeGenerator.generateSql(RuntimeGenerator.java:19) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.sqlgenerator.core.RuntimeGenerator.generateSql(RuntimeGenerator.java:10) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.sqlgenerator.SqlGeneratorChain.generateSql(SqlGeneratorChain.java:30) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:225) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.executor.AbstractExecutor.applyVisitors(AbstractExecutor.java:25) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.access$500(JdbcExecutor.java:36) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:295) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:113) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1277) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1259) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:582) ~[liquibase-core-3.5.3.jar:na]
	... 32 common frames omitted

[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:527)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed for change set db/db-20170709_150135.changelog.xml::1499605306898-1::myuser (generated):
     Reason: java.lang.RuntimeException: Percona exited with 255
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1081)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:856)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151)
	at com.operatornew.gamemanager.SpringBootMysqlApplication.main(SpringBootMysqlApplication.java:10)
	... 6 more
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set db/db-20170709_150135.changelog.xml::1499605306898-1::myuser (generated):
     Reason: java.lang.RuntimeException: Percona exited with 255
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:619)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:79)
	at liquibase.Liquibase.update(Liquibase.java:214)
	at liquibase.Liquibase.update(Liquibase.java:192)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:431)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	... 24 more
Caused by: java.lang.RuntimeException: Percona exited with 255
	at liquibase.ext.percona.PTOnlineSchemaChangeStatement.generate(PTOnlineSchemaChangeStatement.java:210)
	at liquibase.sqlgenerator.core.RuntimeGenerator.generateSql(RuntimeGenerator.java:19)
	at liquibase.sqlgenerator.core.RuntimeGenerator.generateSql(RuntimeGenerator.java:10)
	at liquibase.sqlgenerator.SqlGeneratorChain.generateSql(SqlGeneratorChain.java:30)
	at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:225)
	at liquibase.executor.AbstractExecutor.applyVisitors(AbstractExecutor.java:25)
	at liquibase.executor.jvm.JdbcExecutor.access$500(JdbcExecutor.java:36)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:295)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:113)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1277)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1259)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:582)
	... 32 more
```

**Comment by adangel** [comment]
Ah, ok. So, how this extension gets hold on the password, is kind of a hack: [by reflection](https://github.com/adangel/liquibase-percona/blob/master/src/main/java/liquibase/ext/percona/DatabaseConnectionUtil.java#L76). In your case, it seems, that the JdbcConnection is actually a Proxy... 

Unfortunately, there is no way to set the password here - without changing the code. I spared this property for simpler usage - it most of the time automatically "just" works. And usually, you need to configure the database connection details only once.

Could you post me the relevant Spring configuration, you are using? (Database, SpringLiquibase) Maybe the JdbcConnection doesn't need to be a proxy - that would be the easiest workaround.

But anyway, I think, the code should be updated to handle the cases, where the connection is a proxy. Spring provides some utilities to get hold of the underlying instance, that is proxied - which will be needed here to get hold of the password.

**Comment by jogaco** [comment]
application.properties:
```
# Spring Boot: must use @..@ instead of ${...} https://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html
spring.datasource.url=@jdbc.url@
spring.datasource.username=@jdbc.username@
spring.datasource.password=@jdbc.password@
spring.datasource.driver-class-name=@jdbc.driverClassName@
# Override default liquibase Bean property value: db/changelog/db.changelog-master.yaml
liquibase.changeLog=classpath:db/db.changelog.xml
```

liquibase.properties:
```
url=@jdbc.url@
username=@jdbc.username@
password=@jdbc.password@
driver=@jdbc.driverClassName@
verbose=true
```

You can have a look at the full project, a tutorial I have done on Liquibase, here:

https://github.com/jogaco/spring-boot-mysql-part3

I wanted to add non-blocking pt-osc migrations too :)

**Comment by jogaco** [comment]
I've had a quick look at the code and it seems it requires some modification on Liquibase base code.

**Comment by adangel** [comment]
The proxy contains deep down the original MySQL Jdbc4Connection instance:

    org.apache.tomcat.jdbc.pool.ProxyConnection[org.apache.tomcat.jdbc.pool.PooledConnection[com.mysql.jdbc.JDBC4Connection@63d5abf0]]

So, we should be able to extract it somehow... Spring provides the [Adviced](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/aop/framework/Advised.html#getTargetSource--) interface for AOP proxies, through which you can get the target object.

**Comment by adangel** [comment]
@jogaco I just pushed a fix. Could you please try it, whether it works for you?

Simply add the OSS Repo to your pom.xml:

```
<repositories>
		<repository>
			<id>sonatype-nexus-snapshots</id>
			<name>Sonatype Nexus Snapshots</name>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
</repositories>
```

And use version `1.3.1-SNAPSHOT` of the liquibase-percona extension:

```
<dependency>
    <groupId>com.github.adangel.liquibase.ext</groupId>
    <artifactId>liquibase-percona</artifactId>
    <version>1.3.1-SNAPSHOT</version>
</dependency>
```

**Comment by jogaco** [comment]
Thanks for the fix. It works as expected!

**Comment by adangel** [comment]
Awesome! Thanks for the feedback.
I'll release 1.3.1 end of this week, along with 1.4.0, which will include #13 additionally.

**Comment by adangel** [comment]
1.3.1 is released.

**Comment by vrathore18** [comment]
@adangel : I am still facing the same issue. I am using 1.4.0. Getting  `Couldn't determine the password from JdbcConnection`.
